# Auto-generated build integration
# Generated by parent_repo_integration.py

target_sources(AnimalCrossingVita PRIVATE
    platform/vita_asset_mapping.c
)

target_include_directories(AnimalCrossingVita PRIVATE platform)