#!/usr/bin/env python3
"""
AC-Decomp Asset Symbol Mapping Generator
Scans AC-Decomp source files and generates mapping table for Vita asset bridge
"""

import os
import re
import json
from pathlib import Path

# Patterns to match asset includes
ASSET_INCLUDE_PATTERN = r'#include\s+"assets/([^"]+)"'
SYMBOL_DECLARATION_PATTERN = r'(static\s+)?(\w+)\s+(\w+)\[\]\s*(?:ATTRIBUTE_ALIGN\(\d+\))?\s*=\s*{'

def scan_source_file(file_path):
    """Scan a single source file for asset includes and symbol declarations"""
    assets = []
    
    try:
        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            content = f.read()
            lines = content.split('\n')
            
        current_symbol = None
        
        for i, line in enumerate(lines):
            # Look for symbol declarations
            symbol_match = re.search(SYMBOL_DECLARATION_PATTERN, line)
            if symbol_match:
                is_static = symbol_match.group(1) is not None
                data_type = symbol_match.group(2)
                symbol_name = symbol_match.group(3)
                current_symbol = {
                    'symbol': symbol_name,
                    'type': data_type,
                    'is_static': is_static,
                    'file': str(file_path),
                    'line': i + 1
                }
                continue
            
            # Look for asset includes
            asset_match = re.search(ASSET_INCLUDE_PATTERN, line)
            if asset_match and current_symbol:
                asset_path = asset_match.group(1)
                asset_name = os.path.splitext(asset_path)[0]  # Remove .inc extension
                
                # Determine category based on asset name patterns
                category = classify_asset(asset_name)
                
                asset_entry = {
                    'symbol': current_symbol['symbol'],
                    'type': current_symbol['type'],
                    'is_static': current_symbol['is_static'],
                    'source_file': str(file_path),
                    'source_line': current_symbol['line'],
                    'asset_include': asset_path,
                    'asset_name': asset_name,
                    'category': category,
                    'vita_file': f"{asset_name}.rgba"
                }
                
                assets.append(asset_entry)
                current_symbol = None  # Reset for next symbol
                
    except Exception as e:
        print(f"Error scanning {file_path}: {e}")
        
    return assets

def classify_asset(asset_name):
    """Classify asset into category based on naming patterns"""
    name_lower = asset_name.lower()
    
    # UI/Window assets
    if any(ui_term in name_lower for ui_term in ['win', 'menu', 'btn', 'icon', 'cursor', 'font']):
        return 'ui'
    
    # Character/villager assets  
    if any(char_term in name_lower for char_term in ['npc', 'player', 'villager', 'face', 'hair']):
        return 'characters'
    
    # Items/furniture
    if any(item_term in name_lower for item_term in ['int_', 'obj_', 'tool', 'ftr', 'item']):
        return 'items'
    
    # Environment/world
    if any(env_term in name_lower for env_term in ['grd_', 'field', 'tree', 'flower', 'bridge', 'house']):
        return 'environment'
    
    # Default to environment for unknown
    return 'environment'

def scan_ac_decomp_source(base_path):
    """Scan all AC-Decomp source files for asset mappings"""
    src_path = Path(base_path) / "src"
    
    if not src_path.exists():
        print(f"❌ Source path not found: {src_path}")
        return []
    
    print(f"🔍 Scanning AC-Decomp source files in: {src_path}")
    
    all_assets = []
    file_count = 0
    
    # Scan all .c files recursively
    for c_file in src_path.rglob("*.c"):
        file_count += 1
        assets = scan_source_file(c_file)
        all_assets.extend(assets)
        
        if assets:
            print(f"  📄 {c_file}: {len(assets)} assets")
    
    print(f"✅ Scanned {file_count} source files, found {len(all_assets)} asset mappings")
    return all_assets

def generate_mapping_table(assets):
    """Generate C header file with mapping table"""
    
    # Sort assets by symbol name for easier lookup
    assets.sort(key=lambda x: x['symbol'])
    
    header_content = """#pragma once

// Auto-generated AC-Decomp to Vita asset mapping table
// Generated by generate_asset_mapping.py

#include <stdint.h>
#include <stdbool.h>

typedef struct {
    const char* symbol_name;        // AC-Decomp symbol name
    const char* asset_name;         // Asset file base name  
    const char* vita_file;          // Vita .rgba file name
    const char* category;           // Asset category
    const char* data_type;          // C data type (u8, u16, etc.)
    bool is_static;                 // Was declared static
    const char* source_file;        // Source file containing symbol
    int source_line;                // Line number in source
} ac_asset_mapping_t;

"""
    
    # Generate mapping array
    header_content += f"#define AC_ASSET_MAPPING_COUNT {len(assets)}\n\n"
    header_content += "static const ac_asset_mapping_t g_ac_asset_mappings[] = {\n"
    
    for asset in assets:
        header_content += f'    {{"{asset["symbol"]}", "{asset["asset_name"]}", "{asset["vita_file"]}", '
        header_content += f'"{asset["category"]}", "{asset["type"]}", {"true" if asset["is_static"] else "false"}, '
        header_content += f'"{asset["source_file"]}", {asset["source_line"]}}},\n'
    
    header_content += "};\n\n"
    
    # Generate lookup functions
    header_content += """// Lookup functions
const ac_asset_mapping_t* ac_find_asset_mapping(const char* symbol_name);
const ac_asset_mapping_t* ac_find_asset_by_name(const char* asset_name);
int ac_get_assets_by_category(const char* category, const ac_asset_mapping_t** results, int max_results);

// Asset validation
bool ac_validate_asset_mapping(void);
void ac_print_asset_stats(void);
"""
    
    return header_content

def generate_lookup_implementation(assets):
    """Generate C implementation file with lookup functions"""
    
    impl_content = """#include "ac_asset_mapping.h"
#include <string.h>
#include <stdio.h>

const ac_asset_mapping_t* ac_find_asset_mapping(const char* symbol_name) {
    if (!symbol_name) return NULL;
    
    for (int i = 0; i < AC_ASSET_MAPPING_COUNT; i++) {
        if (strcmp(g_ac_asset_mappings[i].symbol_name, symbol_name) == 0) {
            return &g_ac_asset_mappings[i];
        }
    }
    return NULL;
}

const ac_asset_mapping_t* ac_find_asset_by_name(const char* asset_name) {
    if (!asset_name) return NULL;
    
    for (int i = 0; i < AC_ASSET_MAPPING_COUNT; i++) {
        if (strcmp(g_ac_asset_mappings[i].asset_name, asset_name) == 0) {
            return &g_ac_asset_mappings[i];
        }
    }
    return NULL;
}

int ac_get_assets_by_category(const char* category, const ac_asset_mapping_t** results, int max_results) {
    if (!category || !results) return 0;
    
    int count = 0;
    for (int i = 0; i < AC_ASSET_MAPPING_COUNT && count < max_results; i++) {
        if (strcmp(g_ac_asset_mappings[i].category, category) == 0) {
            results[count++] = &g_ac_asset_mappings[i];
        }
    }
    return count;
}

bool ac_validate_asset_mapping(void) {
    printf("🔍 Validating AC asset mapping...\\n");
    
    int categories[4] = {0}; // ui, characters, items, environment
    
    for (int i = 0; i < AC_ASSET_MAPPING_COUNT; i++) {
        const ac_asset_mapping_t* mapping = &g_ac_asset_mappings[i];
        
        // Count by category
        if (strcmp(mapping->category, "ui") == 0) categories[0]++;
        else if (strcmp(mapping->category, "characters") == 0) categories[1]++;
        else if (strcmp(mapping->category, "items") == 0) categories[2]++;
        else if (strcmp(mapping->category, "environment") == 0) categories[3]++;
    }
    
    printf("✅ Asset mapping validation complete\\n");
    printf("   UI: %d, Characters: %d, Items: %d, Environment: %d\\n", 
           categories[0], categories[1], categories[2], categories[3]);
    printf("   Total assets mapped: %d\\n", AC_ASSET_MAPPING_COUNT);
    
    return true;
}

void ac_print_asset_stats(void) {
    printf("📊 AC-Decomp Asset Mapping Statistics\\n");
    printf("=====================================\\n");
    printf("Total mapped assets: %d\\n", AC_ASSET_MAPPING_COUNT);
    
    // Print sample mappings
    printf("\\nSample mappings:\\n");
    for (int i = 0; i < 5 && i < AC_ASSET_MAPPING_COUNT; i++) {
        const ac_asset_mapping_t* mapping = &g_ac_asset_mappings[i];
        printf("  %s -> %s (%s)\\n", mapping->symbol_name, mapping->vita_file, mapping->category);
    }
}
"""
    
    return impl_content

def main():
    """Main function to generate asset mapping"""
    
    # Determine AC-Decomp source path
    script_dir = Path(__file__).parent
    ac_decomp_paths = [
        script_dir.parent.parent / "ac-decomp-upstream",
        script_dir.parent.parent / "ac-decomp-source",
        script_dir.parent.parent / "src"
    ]
    
    ac_decomp_path = None
    for path in ac_decomp_paths:
        if path.exists():
            ac_decomp_path = path
            break
    
    if not ac_decomp_path:
        print("❌ Could not find AC-Decomp source directory")
        return False
    
    print(f"🎮 AC-Decomp Asset Mapping Generator")
    print(f"Using source: {ac_decomp_path}")
    
    # Scan source files
    assets = scan_ac_decomp_source(ac_decomp_path)
    
    if not assets:
        print("❌ No assets found")
        return False
    
    # Generate output files
    output_dir = script_dir
    header_file = output_dir / "ac_asset_mapping.h"
    impl_file = output_dir / "ac_asset_mapping.c"
    json_file = output_dir / "ac_asset_mapping.json"
    
    # Write header file
    with open(header_file, 'w') as f:
        f.write(generate_mapping_table(assets))
    
    # Write implementation file  
    with open(impl_file, 'w') as f:
        f.write(generate_lookup_implementation(assets))
    
    # Write JSON for analysis
    with open(json_file, 'w') as f:
        json.dump(assets, f, indent=2)
    
    # Print statistics
    categories = {}
    for asset in assets:
        cat = asset['category']
        categories[cat] = categories.get(cat, 0) + 1
    
    print(f"\n✅ Generated asset mapping files:")
    print(f"   📄 {header_file}")
    print(f"   📄 {impl_file}")
    print(f"   📄 {json_file}")
    print(f"\n📊 Asset Statistics:")
    for cat, count in sorted(categories.items()):
        print(f"   {cat}: {count} assets")
    print(f"   Total: {len(assets)} assets")
    
    return True

if __name__ == "__main__":
    success = main()
    exit(0 if success else 1) 