/**
 * @file gbi.h
 * @brief N64 Graphics Binary Interface (GBI) definitions
 *
 * This header defines the N64 display list command format.
 * These commands are generated by the game code (Layer 1) and
 * interpreted by the GBI interpreter (Layer 3) for OpenGL rendering.
 *
 * Part of Layer 2/3 interface.
 */
#ifndef PC_GBI_H
#define PC_GBI_H

#include "platform.h"

/* ============================================================================
 * Display List Types
 * ============================================================================ */

/* Generic Gfx Packet - two 32-bit words */
typedef struct {
    u32 w0;
    u32 w1;
} Gwords;

/*
 * This union is the fundamental type of the display list.
 * It is exactly 64 bits in size.
 */
typedef union {
    Gwords words;
    u64 raw;        /* For raw 64-bit access */
    struct {
        u32 w0;
        u32 w1;
    };
    long long int force_structure_alignment;
} Gfx;

/* Pointer to display list */
typedef Gfx* Gfx_p;

/* Matrix type (4x4 fixed point) */
typedef s32 Mtx_t[4][4];
typedef union {
    Mtx_t m;
    struct {
        u16 intPart[4][4];
        u16 fracPart[4][4];
    } fp;
    long long int force_structure_alignment;
} Mtx;

/* Vertex structure - color version */
typedef struct {
    s16 ob[3];      /* Position */
    u16 flag;       /* Flag */
    s16 tc[2];      /* Texture coordinates */
    u8 cn[4];       /* Color RGBA */
} Vtx_t;

/* Vertex structure - normal version */
typedef struct {
    s16 ob[3];      /* Position */
    u16 flag;       /* Flag */
    s16 tc[2];      /* Texture coordinates */
    s8 n[3];        /* Normal XYZ */
    u8 a;           /* Alpha */
} Vtx_tn;

typedef union {
    Vtx_t v;        /* Use for colors */
    Vtx_tn n;       /* Use for normals */
    long long int force_structure_alignment;
} Vtx;

/* Light structure */
typedef struct {
    u8 col[3];      /* Color */
    s8 pad1;
    u8 colc[3];     /* Color copy */
    s8 pad2;
    s8 dir[3];      /* Direction */
    s8 pad3;
} Light_t;

typedef union {
    Light_t l;
    long long int force_structure_alignment[2];
} Light;

/* Ambient light */
typedef struct {
    u8 col[3];
    s8 pad1;
    u8 colc[3];
    s8 pad2;
} Ambient_t;

typedef union {
    Ambient_t l;
    long long int force_structure_alignment;
} Ambient;

/* Combined lights structure */
typedef struct {
    Ambient a;
    Light l[7];
} Lights7;

typedef struct {
    Ambient a;
    Light l[1];
} Lights1;

/* Viewport structure */
typedef struct {
    short vscale[4];    /* Scale, 2 bits fraction */
    short vtrans[4];    /* Translate, 2 bits fraction */
} Vp_t;

typedef union {
    Vp_t vp;
    long long int force_structure_alignment;
} Vp;

/* Hilite structure (for specular highlights) */
typedef struct {
    int x1, y1, x2, y2;  /* Texture offsets for highlight 1/2 */
} Hilite_t;

typedef union {
    Hilite_t h;
    long int force_structure_alignment[4];
} Hilite;

/* LookAt structure (for texture coordinate generation) */
typedef struct {
    Light l[2];
} LookAt;

/* Set image command structure */
typedef struct {
    unsigned int cmd:8;
    unsigned int fmt:3;
    unsigned int siz:2;
    unsigned int pad:7;
    unsigned int wd:12;
    unsigned int dram;
} Gsetimg;

/* ============================================================================
 * GBI Command Opcodes (F3DEX2 microcode)
 * ============================================================================ */

/* RDP commands (0x00-0x3F) */
#define G_NOOP              0x00
#define G_RDPHALF_2         0xF1
#define G_SETOTHERMODE_H    0xE3
#define G_SETOTHERMODE_L    0xE2
#define G_RDPHALF_1         0xE1
#define G_SPNOOP            0xE0
#define G_ENDDL             0xDF
#define G_DL                0xDE
#define G_LOAD_UCODE        0xDD
#define G_MOVEMEM           0xDC
#define G_MOVEWORD          0xDB
#define G_MTX               0xDA
#define G_GEOMETRYMODE      0xD9
#define G_POPMTX            0xD8
#define G_TEXTURE           0xD7
#define G_DMA_IO            0xD6
#define G_SPECIAL_1         0xD5
#define G_SPECIAL_2         0xD4
#define G_SPECIAL_3         0xD3

#define G_VTX               0x01
#define G_MODIFYVTX         0x02
#define G_CULLDL            0x03
#define G_BRANCH_Z          0x04
#define G_TRI1              0x05
#define G_TRI2              0x06
#define G_QUAD              0x07
#define G_LINE3D            0x08

/* RDP commands */
#define G_SETCIMG           0xFF
#define G_SETZIMG           0xFE
#define G_SETTIMG           0xFD
#define G_SETCOMBINE        0xFC
#define G_SETENVCOLOR       0xFB
#define G_SETPRIMCOLOR      0xFA
#define G_SETBLENDCOLOR     0xF9
#define G_SETFOGCOLOR       0xF8
#define G_SETFILLCOLOR      0xF7
#define G_FILLRECT          0xF6
#define G_SETTILE           0xF5
#define G_LOADTILE          0xF4
#define G_LOADBLOCK         0xF3
#define G_SETTILESIZE       0xF2
#define G_LOADTLUT          0xF0
#define G_RDPSETOTHERMODE   0xEF
#define G_SETPRIMDEPTH      0xEE
#define G_SETSCISSOR        0xED
#define G_SETCONVERT        0xEC
#define G_SETKEYR           0xEB
#define G_SETKEYGB          0xEA
#define G_RDPFULLSYNC       0xE9
#define G_RDPTILESYNC       0xE8
#define G_RDPPIPESYNC       0xE7
#define G_RDPLOADSYNC       0xE6
#define G_TEXRECTFLIP       0xE5
#define G_TEXRECT           0xE4

/* ============================================================================
 * Geometry Mode Flags
 * ============================================================================ */

#define G_ZBUFFER               0x00000001
#define G_SHADE                 0x00000004
#define G_CULL_FRONT            0x00000200
#define G_CULL_BACK             0x00000400
#define G_CULL_BOTH             0x00000600
#define G_FOG                   0x00010000
#define G_LIGHTING              0x00020000
#define G_TEXTURE_GEN           0x00040000
#define G_TEXTURE_GEN_LINEAR    0x00080000
#define G_LOD                   0x00100000
#define G_SHADING_SMOOTH        0x00200000
#define G_CLIPPING              0x00800000

/* ============================================================================
 * Texture Formats
 * ============================================================================ */

#define G_IM_FMT_RGBA   0
#define G_IM_FMT_YUV    1
#define G_IM_FMT_CI     2
#define G_IM_FMT_IA     3
#define G_IM_FMT_I      4

#define G_IM_SIZ_4b     0
#define G_IM_SIZ_8b     1
#define G_IM_SIZ_16b    2
#define G_IM_SIZ_32b    3

/* ============================================================================
 * Moveword Indices and Offsets (F3DEX_GBI_2)
 * ============================================================================ */

/* MW (MoveWord) indices */
#define G_MW_MATRIX         0x00
#define G_MW_NUMLIGHT       0x02
#define G_MW_CLIP           0x04
#define G_MW_SEGMENT        0x06
#define G_MW_FOG            0x08
#define G_MW_LIGHTCOL       0x0A
#define G_MW_FORCEMTX       0x0C
#define G_MW_PERSPNORM      0x0E

/* MV (MoveMem) indices (F3DEX_GBI_2) */
#define G_MV_VIEWPORT       8
#define G_MV_LIGHT          10
#define G_MV_MATRIX         14

/* MVO (MoveMem Offsets) */
#define G_MVO_LOOKATX       (0*24)
#define G_MVO_LOOKATY       (1*24)

/* MWO (MoveWord Offsets) */
#define G_MWO_NUMLIGHT      0x00
#define G_MWO_CLIP_RNX      0x04
#define G_MWO_CLIP_RNY      0x0C
#define G_MWO_CLIP_RPX      0x14
#define G_MWO_CLIP_RPY      0x1C
#define G_MWO_SEGMENT_0     0x00
#define G_MWO_SEGMENT_1     0x04
#define G_MWO_SEGMENT_2     0x08
#define G_MWO_SEGMENT_3     0x0C
#define G_MWO_SEGMENT_4     0x10
#define G_MWO_SEGMENT_5     0x14
#define G_MWO_SEGMENT_6     0x18
#define G_MWO_SEGMENT_7     0x1C
#define G_MWO_SEGMENT_8     0x20
#define G_MWO_SEGMENT_9     0x24
#define G_MWO_SEGMENT_A     0x28
#define G_MWO_SEGMENT_B     0x2C
#define G_MWO_SEGMENT_C     0x30
#define G_MWO_SEGMENT_D     0x34
#define G_MWO_SEGMENT_E     0x38
#define G_MWO_SEGMENT_F     0x3C
#define G_MWO_FOG           0x00
#define G_MWO_aLIGHT_1      0x00
#define G_MWO_bLIGHT_1      0x04
#define G_MWO_aLIGHT_2      0x18
#define G_MWO_bLIGHT_2      0x1C
#define G_MWO_aLIGHT_3      0x30
#define G_MWO_bLIGHT_3      0x34
#define G_MWO_aLIGHT_4      0x48
#define G_MWO_bLIGHT_4      0x4C
#define G_MWO_aLIGHT_5      0x60
#define G_MWO_bLIGHT_5      0x64
#define G_MWO_aLIGHT_6      0x78
#define G_MWO_bLIGHT_6      0x7C
#define G_MWO_aLIGHT_7      0x90
#define G_MWO_bLIGHT_7      0x94
#define G_MWO_aLIGHT_8      0xA8
#define G_MWO_bLIGHT_8      0xAC
#define G_MWO_MATRIX_XX_XY_I    0x00
#define G_MWO_MATRIX_XZ_XW_I    0x04
#define G_MWO_MATRIX_YX_YY_I    0x08
#define G_MWO_MATRIX_YZ_YW_I    0x0C
#define G_MWO_MATRIX_ZX_ZY_I    0x10
#define G_MWO_MATRIX_ZZ_ZW_I    0x14
#define G_MWO_MATRIX_WX_WY_I    0x18
#define G_MWO_MATRIX_WZ_WW_I    0x1C
#define G_MWO_MATRIX_XX_XY_F    0x20
#define G_MWO_MATRIX_XZ_XW_F    0x24
#define G_MWO_MATRIX_YX_YY_F    0x28
#define G_MWO_MATRIX_YZ_YW_F    0x2C
#define G_MWO_MATRIX_ZX_ZY_F    0x30
#define G_MWO_MATRIX_ZZ_ZW_F    0x34
#define G_MWO_MATRIX_WX_WY_F    0x38
#define G_MWO_MATRIX_WZ_WW_F    0x3C
#define G_MWO_POINT_RGBA        0x10
#define G_MWO_POINT_ST          0x14
#define G_MWO_POINT_XYSCREEN    0x18
#define G_MWO_POINT_ZSCREEN     0x1C

/* ============================================================================
 * Display List Building Macros (F3DEX2 style)
 * ============================================================================ */

/* Bit shifting helpers */
#define _SHIFTL(v, s, w)    ((u32)(((u32)(v) & ((0x01 << (w)) - 1)) << (s)))
#define _SHIFTR(v, s, w)    ((u32)(((u32)(v) >> (s)) & ((0x01 << (w)) - 1)))

/* No-op command */
#define gDPNoOp(pkt) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = 0; \
    _g->words.w1 = 0; \
}

/* End display list */
#define gSPEndDisplayList(pkt) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_ENDDL, 24, 8); \
    _g->words.w1 = 0; \
}

/* Load vertices (F3DEX2 format) */
#define gSPVertex(pkt, v, n, v0) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_VTX, 24, 8) | _SHIFTL((n), 12, 8) | _SHIFTL((v0)+(n), 1, 7); \
    _g->words.w1 = (u32)(uintptr_t)(v); \
}

/* Draw single triangle (F3DEX2 format) */
#define gSP1Triangle(pkt, v0, v1, v2, flag) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_TRI1, 24, 8); \
    _g->words.w1 = _SHIFTL((v0)*2, 16, 8) | _SHIFTL((v1)*2, 8, 8) | _SHIFTL((v2)*2, 0, 8); \
}

/* Draw two triangles */
#define gSP2Triangles(pkt, v00, v01, v02, flag0, v10, v11, v12, flag1) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_TRI2, 24, 8) | \
                   _SHIFTL((v00)*2, 16, 8) | _SHIFTL((v01)*2, 8, 8) | _SHIFTL((v02)*2, 0, 8); \
    _g->words.w1 = _SHIFTL((v10)*2, 16, 8) | _SHIFTL((v11)*2, 8, 8) | _SHIFTL((v12)*2, 0, 8); \
}

/* Call display list */
#define gSPDisplayList(pkt, dl) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_DL, 24, 8); \
    _g->words.w1 = (u32)(uintptr_t)(dl); \
}

/* Branch to display list (without return) */
#define gSPBranchList(pkt, dl) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_DL, 24, 8) | _SHIFTL(1, 16, 8); \
    _g->words.w1 = (u32)(uintptr_t)(dl); \
}

/* Cull display list based on bounding box vertices */
#define gSPCullDisplayList(pkt, vstart, vend) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_CULLDL, 24, 8) | _SHIFTL((vstart)*2, 0, 16); \
    _g->words.w1 = _SHIFTL((vend)*2, 0, 16); \
}

/* Set segment register
 * Note: This codebase uses G_MWO_SEGMENT_* constants which are already offsets
 * (e.g., G_MWO_SEGMENT_A = 0x28 for segment 10), so we don't multiply by 4.
 */
#define gSPSegment(pkt, seg, base) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_MOVEWORD, 24, 8) | _SHIFTL(0x06, 16, 8) | _SHIFTL((seg), 0, 16); \
    _g->words.w1 = (u32)(uintptr_t)(base); \
}

/* Pipe sync */
#define gDPPipeSync(pkt) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_RDPPIPESYNC, 24, 8); \
    _g->words.w1 = 0; \
}

/* Full sync */
#define gDPFullSync(pkt) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_RDPFULLSYNC, 24, 8); \
    _g->words.w1 = 0; \
}

/* ============================================================================
 * Texture Tile Constants
 * ============================================================================ */
#define G_TX_RENDERTILE     0
#define G_TX_LOADTILE       7

/* Texture wrap modes */
#define G_TX_NOMIRROR       0
#define G_TX_WRAP           0
#define G_TX_MIRROR         1
#define G_TX_CLAMP          2
#define G_TX_NOMASK         0
#define G_TX_NOLOD          0

/* ============================================================================
 * Other Mode Flags
 * ============================================================================ */

/* Alpha dither */
#define G_AD_PATTERN        0x00000000
#define G_AD_NOTPATTERN     0x00000010
#define G_AD_NOISE          0x00000020
#define G_AD_DISABLE        0x00000030

/* Color dither */
#define G_CD_MAGICSQ        0x00000000
#define G_CD_BAYER          0x00000040
#define G_CD_NOISE          0x00000080
#define G_CD_DISABLE        0x000000C0

/* Chroma key */
#define G_CK_NONE           0x00000000
#define G_CK_KEY            0x00000100

/* Texture convert */
#define G_TC_CONV           0x00000000
#define G_TC_FILTCONV       0x00000A00
#define G_TC_FILT           0x00001400

/* Texture filter */
#define G_TF_POINT          0x00000000
#define G_TF_AVERAGE        0x00003000
#define G_TF_BILERP         0x00002000

/* Texture LOD */
#define G_TL_TILE           0x00000000
#define G_TL_LOD            0x00004000

/* Texture detail */
#define G_TD_CLAMP          0x00000000
#define G_TD_SHARPEN        0x00008000
#define G_TD_DETAIL         0x00010000

/* Texture perspective */
#define G_TP_NONE           0x00000000
#define G_TP_PERSP          0x00080000

/* Cycle type */
#define G_CYC_1CYCLE        0x00000000
#define G_CYC_2CYCLE        0x00100000
#define G_CYC_COPY          0x00200000
#define G_CYC_FILL          0x00300000

/* Pipeline mode */
#define G_PM_1PRIMITIVE     0x00000000
#define G_PM_NPRIMITIVE     0x00800000

/* ============================================================================
 * Combine Mode Color Inputs
 * ============================================================================ */

#define COMBINED        0
#define TEXEL0          1
#define TEXEL1          2
#define PRIMITIVE       3
#define SHADE           4
#define ENVIRONMENT     5
#define CENTER          6
#define SCALE           6
#define COMBINED_ALPHA  7
#define TEXEL0_ALPHA    8
#define TEXEL1_ALPHA    9
#define PRIMITIVE_ALPHA 10
#define SHADE_ALPHA     11
#define ENV_ALPHA       12
#define LOD_FRACTION    13
#define PRIM_LOD_FRAC   14
#define NOISE           7
#define K4              7
#define K5              15
#define G_CCMUX_1       6
#define G_CCMUX_0       31

/* Common combine modes */
#define G_CC_PRIMITIVE          0, 0, 0, PRIMITIVE, 0, 0, 0, PRIMITIVE
#define G_CC_SHADE              0, 0, 0, SHADE, 0, 0, 0, SHADE
#define G_CC_MODULATEI          TEXEL0, 0, SHADE, 0, 0, 0, 0, SHADE
#define G_CC_MODULATEIA         TEXEL0, 0, SHADE, 0, TEXEL0, 0, SHADE, 0
#define G_CC_DECALRGB           0, 0, 0, TEXEL0, 0, 0, 0, SHADE
#define G_CC_DECALRGBA          0, 0, 0, TEXEL0, 0, 0, 0, TEXEL0
#define G_CC_BLENDPE            PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, TEXEL0, 0, SHADE, 0
#define G_CC_BLENDPEDECALA      PRIMITIVE, ENVIRONMENT, TEXEL0, ENVIRONMENT, 0, 0, 0, TEXEL0

/* ============================================================================
 * Additional GBI Macros - Dynamic (pkt++)
 * ============================================================================ */

/* DMA operation */
#define gDma1p(pkt, c, s, l, p) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL((c), 24, 8) | _SHIFTL((p), 16, 8) | _SHIFTL((l), 0, 16); \
    _g->words.w1 = (u32)(uintptr_t)(s); \
}

/* Set other mode (low and high words) */
#define gDPSetOtherMode(pkt, mode0, mode1) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_RDPSETOTHERMODE, 24, 8) | (u32)(mode0); \
    _g->words.w1 = (u32)(mode1); \
}

/* Set primitive color */
#define gDPSetPrimColor(pkt, minlevel, lodfrac, r, g, b, a) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETPRIMCOLOR, 24, 8) | _SHIFTL((minlevel), 8, 8) | _SHIFTL((lodfrac), 0, 8); \
    _g->words.w1 = _SHIFTL((r), 24, 8) | _SHIFTL((g), 16, 8) | _SHIFTL((b), 8, 8) | _SHIFTL((a), 0, 8); \
}

/* Set environment color */
#define gDPSetEnvColor(pkt, r, g, b, a) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETENVCOLOR, 24, 8); \
    _g->words.w1 = _SHIFTL((r), 24, 8) | _SHIFTL((g), 16, 8) | _SHIFTL((b), 8, 8) | _SHIFTL((a), 0, 8); \
}

/* Set fill color */
#define gDPSetFillColor(pkt, c) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETFILLCOLOR, 24, 8); \
    _g->words.w1 = (u32)(c); \
}

/* Fill rectangle - N64 format: 10-bit coordinates at bits 23:14 and 11:2 */
#define gDPFillRectangle(pkt, ulx, uly, lrx, lry) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_FILLRECT, 24, 8) | _SHIFTL((lrx), 14, 10) | _SHIFTL((lry), 2, 10); \
    _g->words.w1 = _SHIFTL((ulx), 14, 10) | _SHIFTL((uly), 2, 10); \
}

/* Set combine mode - builds the 64-bit combine word */
#define gDPSetCombineLERP(pkt, a0, b0, c0, d0, Aa0, Ab0, Ac0, Ad0, \
                                a1, b1, c1, d1, Aa1, Ab1, Ac1, Ad1) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETCOMBINE, 24, 8) | \
                   _SHIFTL((a0), 20, 4) | _SHIFTL((c0), 15, 5) | \
                   _SHIFTL((Aa0), 12, 3) | _SHIFTL((Ac0), 9, 3) | \
                   _SHIFTL((a1), 5, 4) | _SHIFTL((c1), 0, 5); \
    _g->words.w1 = _SHIFTL((b0), 28, 4) | _SHIFTL((b1), 24, 4) | \
                   _SHIFTL((Aa1), 21, 3) | _SHIFTL((Ac1), 18, 3) | \
                   _SHIFTL((d0), 15, 3) | _SHIFTL((Ab0), 12, 3) | \
                   _SHIFTL((Ad0), 9, 3) | _SHIFTL((d1), 6, 3) | \
                   _SHIFTL((Ab1), 3, 3) | _SHIFTL((Ad1), 0, 3); \
}

#define gDPSetCombineMode(pkt, a, b) gDPSetCombineLERP(pkt, a, b)

/* Texture rectangle - draws a textured rectangle */
#define gSPTextureRectangle(pkt, xl, yl, xh, yh, tile, s, t, dsdx, dtdy) \
{ \
    Gfx* _g0 = (Gfx*)(pkt); \
    _g0->words.w0 = _SHIFTL(G_TEXRECT, 24, 8) | _SHIFTL((xh), 12, 12) | _SHIFTL((yh), 0, 12); \
    _g0->words.w1 = _SHIFTL((tile), 24, 3) | _SHIFTL((xl), 12, 12) | _SHIFTL((yl), 0, 12); \
    Gfx* _g1 = (Gfx*)((pkt)+1); \
    _g1->words.w0 = _SHIFTL((s), 16, 16) | _SHIFTL((t), 0, 16); \
    _g1->words.w1 = _SHIFTL((dsdx), 16, 16) | _SHIFTL((dtdy), 0, 16); \
}

/* ============================================================================
 * Static GBI Macros (for static Gfx arrays)
 * ============================================================================ */

#define gsSPEndDisplayList() \
    {{ _SHIFTL(G_ENDDL, 24, 8), 0 }}

#define gsDPSetOtherMode(mode0, mode1) \
    {{ _SHIFTL(G_RDPSETOTHERMODE, 24, 8) | (u32)(mode0), (u32)(mode1) }}

#define gsDPSetCombineLERP(a0, b0, c0, d0, Aa0, Ab0, Ac0, Ad0, \
                           a1, b1, c1, d1, Aa1, Ab1, Ac1, Ad1) \
    {{ _SHIFTL(G_SETCOMBINE, 24, 8) | \
       _SHIFTL((a0), 20, 4) | _SHIFTL((c0), 15, 5) | \
       _SHIFTL((Aa0), 12, 3) | _SHIFTL((Ac0), 9, 3) | \
       _SHIFTL((a1), 5, 4) | _SHIFTL((c1), 0, 5), \
       _SHIFTL((b0), 28, 4) | _SHIFTL((b1), 24, 4) | \
       _SHIFTL((Aa1), 21, 3) | _SHIFTL((Ac1), 18, 3) | \
       _SHIFTL((d0), 15, 3) | _SHIFTL((Ab0), 12, 3) | \
       _SHIFTL((Ad0), 9, 3) | _SHIFTL((d1), 6, 3) | \
       _SHIFTL((Ab1), 3, 3) | _SHIFTL((Ad1), 0, 3) }}

#define gsDPSetCombineMode(a, b) gsDPSetCombineLERP(a, b)

#define gsDPPipeSync() \
    {{ _SHIFTL(G_RDPPIPESYNC, 24, 8), 0 }}

#define gsDPFullSync() \
    {{ _SHIFTL(G_RDPFULLSYNC, 24, 8), 0 }}

#define gsSPTextureRectangle(xl, yl, xh, yh, tile, s, t, dsdx, dtdy) \
    {{ _SHIFTL(G_TEXRECT, 24, 8) | _SHIFTL((xh), 12, 12) | _SHIFTL((yh), 0, 12), \
       _SHIFTL((tile), 24, 3) | _SHIFTL((xl), 12, 12) | _SHIFTL((yl), 0, 12) }}, \
    {{ _SHIFTL((s), 16, 16) | _SHIFTL((t), 0, 16), \
       _SHIFTL((dsdx), 16, 16) | _SHIFTL((dtdy), 0, 16) }}

/*
 * Static vertex load - NOTE: On 64-bit systems, the pointer 'v' is truncated!
 * For PC port, prefer runtime display list construction with gSPVertex().
 * F3DEX2 format.
 */
#define gsSPVertex(v, n, v0) \
    {{ _SHIFTL(G_VTX, 24, 8) | _SHIFTL((n), 12, 8) | _SHIFTL((v0)+(n), 1, 7), \
       (u32)(uintptr_t)(v) }}

/*
 * Static display list call - NOTE: On 64-bit systems, the pointer 'dl' is truncated!
 * For PC port, prefer runtime display list construction with gSPDisplayList().
 */
#define gsSPDisplayList(dl) \
    {{ _SHIFTL(G_DL, 24, 8), (u32)(uintptr_t)(dl) }}

/* Static branch list */
#define gsSPBranchList(dl) \
    {{ _SHIFTL(G_DL, 24, 8) | _SHIFTL(1, 16, 8), (u32)(uintptr_t)(dl) }}

/* Static cull display list */
#define gsSPCullDisplayList(vstart, vend) \
    {{ _SHIFTL(G_CULLDL, 24, 8) | _SHIFTL((vstart)*2, 0, 16), \
       _SHIFTL((vend)*2, 0, 16) }}

/* ============================================================================
 * Geometry Mode Macros
 * ============================================================================ */

#define gSPSetGeometryMode(pkt, mode) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_GEOMETRYMODE, 24, 8) | _SHIFTL(~0, 0, 24); \
    _g->words.w1 = (u32)(mode); \
}

#define gSPClearGeometryMode(pkt, mode) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_GEOMETRYMODE, 24, 8) | _SHIFTL(~(u32)(mode), 0, 24); \
    _g->words.w1 = 0; \
}

#define gsSPSetGeometryMode(mode) \
    {{ _SHIFTL(G_GEOMETRYMODE, 24, 8) | _SHIFTL(~0, 0, 24), (u32)(mode) }}

#define gsSPClearGeometryMode(mode) \
    {{ _SHIFTL(G_GEOMETRYMODE, 24, 8) | _SHIFTL(~(u32)(mode), 0, 24), 0 }}

#define gSPLoadGeometryMode(pkt, mode) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_GEOMETRYMODE, 24, 8); \
    _g->words.w1 = (u32)(mode); \
}

#define gsSPLoadGeometryMode(mode) \
    {{ _SHIFTL(G_GEOMETRYMODE, 24, 8), (u32)(mode) }}

/* ============================================================================
 * Texture Macros
 * ============================================================================ */

#define gSPTexture(pkt, s, t, level, tile, on) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_TEXTURE, 24, 8) | _SHIFTL((level), 11, 3) | \
                   _SHIFTL((tile), 8, 3) | _SHIFTL((on), 1, 7); \
    _g->words.w1 = _SHIFTL((s), 16, 16) | _SHIFTL((t), 0, 16); \
}

#define gsSPTexture(s, t, level, tile, on) \
    {{ _SHIFTL(G_TEXTURE, 24, 8) | _SHIFTL((level), 11, 3) | \
       _SHIFTL((tile), 8, 3) | _SHIFTL((on), 1, 7), \
       _SHIFTL((s), 16, 16) | _SHIFTL((t), 0, 16) }}

#define G_ON    1
#define G_OFF   0

/* ============================================================================
 * Quadrangle Helper Macros (F3DEX2)
 * ============================================================================ */

#define G_QUAD  0x07

#define __gsSP1Quadrangle_w1f(v0, v1, v2, v3, flag) \
    (_SHIFTL((v0)*2, 16, 8) | _SHIFTL((v1)*2, 8, 8) | _SHIFTL((v2)*2, 0, 8))

#define __gsSP1Quadrangle_w2f(v0, v1, v2, v3, flag) \
    (_SHIFTL((v0)*2, 16, 8) | _SHIFTL((v2)*2, 8, 8) | _SHIFTL((v3)*2, 0, 8))

#define gSP1Quadrangle(pkt, v0, v1, v2, v3, flag) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_TRI2, 24, 8) | __gsSP1Quadrangle_w1f(v0, v1, v2, v3, flag); \
    _g->words.w1 = __gsSP1Quadrangle_w2f(v0, v1, v2, v3, flag); \
}

#define gsSP1Quadrangle(v0, v1, v2, v3, flag) \
    {{ _SHIFTL(G_TRI2, 24, 8) | __gsSP1Quadrangle_w1f(v0, v1, v2, v3, flag), \
       __gsSP1Quadrangle_w2f(v0, v1, v2, v3, flag) }}

/* ============================================================================
 * Texture Loading Macros
 * ============================================================================ */

#define G_TX_DXT_FRAC   11

#define gDPSetTextureImage(pkt, fmt, siz, width, addr) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETTIMG, 24, 8) | _SHIFTL((fmt), 21, 3) | \
                   _SHIFTL((siz), 19, 2) | _SHIFTL((width)-1, 0, 12); \
    _g->words.w1 = (u32)(uintptr_t)(addr); \
}

#define gDPSetTile(pkt, fmt, siz, line, tmem, tile, palette, cmt, maskt, shiftt, cms, masks, shifts) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETTILE, 24, 8) | _SHIFTL((fmt), 21, 3) | \
                   _SHIFTL((siz), 19, 2) | _SHIFTL((line), 9, 9) | _SHIFTL((tmem), 0, 9); \
    _g->words.w1 = _SHIFTL((tile), 24, 3) | _SHIFTL((palette), 20, 4) | \
                   _SHIFTL((cmt), 18, 2) | _SHIFTL((maskt), 14, 4) | _SHIFTL((shiftt), 10, 4) | \
                   _SHIFTL((cms), 8, 2) | _SHIFTL((masks), 4, 4) | _SHIFTL((shifts), 0, 4); \
}

#define gDPLoadTile(pkt, tile, uls, ult, lrs, lrt) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_LOADTILE, 24, 8) | _SHIFTL((uls), 12, 12) | _SHIFTL((ult), 0, 12); \
    _g->words.w1 = _SHIFTL((tile), 24, 3) | _SHIFTL((lrs), 12, 12) | _SHIFTL((lrt), 0, 12); \
}

#define gDPSetTileSize(pkt, tile, uls, ult, lrs, lrt) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETTILESIZE, 24, 8) | _SHIFTL((uls), 12, 12) | _SHIFTL((ult), 0, 12); \
    _g->words.w1 = _SHIFTL((tile), 24, 3) | _SHIFTL((lrs), 12, 12) | _SHIFTL((lrt), 0, 12); \
}

#define gDPLoadTextureTile(pkt, timg, fmt, siz, width, height, \
                           uls, ult, lrs, lrt, pal, cms, cmt, masks, maskt, shifts, shiftt) \
{ \
    gDPSetTextureImage(pkt, fmt, siz, width, timg); \
    gDPSetTile(pkt, fmt, siz, (((((lrs)-(uls)+1) * (1 << (siz))) + 7) >> 3), 0, \
               G_TX_LOADTILE, 0, cmt, maskt, shiftt, cms, masks, shifts); \
    gDPLoadTile(pkt, G_TX_LOADTILE, (uls)<<2, (ult)<<2, (lrs)<<2, (lrt)<<2); \
    gDPSetTile(pkt, fmt, siz, (((((lrs)-(uls)+1) * (1 << (siz))) + 7) >> 3), 0, \
               G_TX_RENDERTILE, pal, cmt, maskt, shiftt, cms, masks, shifts); \
    gDPSetTileSize(pkt, G_TX_RENDERTILE, (uls)<<2, (ult)<<2, (lrs)<<2, (lrt)<<2); \
}

/* Simpler version - just set up for tile loading */
#define gDPLoadTextureBlock(pkt, timg, fmt, siz, width, height, pal, \
                            cms, cmt, masks, maskt, shifts, shiftt) \
    gDPLoadTextureTile(pkt, timg, fmt, siz, width, height, \
                       0, 0, (width)-1, (height)-1, pal, cms, cmt, masks, maskt, shifts, shiftt)

/* ============================================================================
 * Matrix Macros
 * ============================================================================ */

#define G_MTX_NOPUSH        0x00
#define G_MTX_PUSH          0x01
#define G_MTX_MUL           0x00
#define G_MTX_LOAD          0x02
#define G_MTX_MODELVIEW     0x00
#define G_MTX_PROJECTION    0x04

#define gSPMatrix(pkt, mtx, param) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_MTX, 24, 8) | _SHIFTL((param) ^ G_MTX_PUSH, 0, 8); \
    _g->words.w1 = (u32)(uintptr_t)(mtx); \
}

#define gsSPMatrix(mtx, param) \
    {{ _SHIFTL(G_MTX, 24, 8) | _SHIFTL((param) ^ G_MTX_PUSH, 0, 8), (u32)(uintptr_t)(mtx) }}

#define gSPPopMatrix(pkt, param) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_POPMTX, 24, 8); \
    _g->words.w1 = 64; \
}

#define gsSPPopMatrix(param) \
    {{ _SHIFTL(G_POPMTX, 24, 8), 64 }}

/* ============================================================================
 * MoveWord/DMA Macros
 * ============================================================================ */

#define gDma1p(pkt, c, s, l, p) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL((c), 24, 8) | _SHIFTL((p), 16, 8) | _SHIFTL((l), 0, 16); \
    _g->words.w1 = (u32)(uintptr_t)(s); \
}

#define gsDma1p(c, s, l, p) \
    {{ _SHIFTL((c), 24, 8) | _SHIFTL((p), 16, 8) | _SHIFTL((l), 0, 16), (u32)(uintptr_t)(s) }}

#define gMoveWd(pkt, index, offset, data) \
    gDma1p((pkt), G_MOVEWORD, data, offset, index)

#define gsMoveWd(index, offset, data) \
    gsDma1p(G_MOVEWORD, data, offset, index)

/* Perspective normalize */
#define gSPPerspNormalize(pkt, s) gMoveWd(pkt, G_MW_PERSPNORM, 0, (s))
#define gsSPPerspNormalize(s)     gsMoveWd(G_MW_PERSPNORM, 0, (s))

/* DMA 2-parameter macro (F3DEX_GBI_2) */
#define gDma2p(pkt, c, adrs, len, idx, ofs) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL((c), 24, 8) | _SHIFTL(((len)-1)/8, 19, 5) | \
                   _SHIFTL((ofs)/8, 8, 8) | _SHIFTL((idx), 0, 8); \
    _g->words.w1 = (u32)(uintptr_t)(adrs); \
}

#define gsDma2p(c, adrs, len, idx, ofs) \
    {{ _SHIFTL((c), 24, 8) | _SHIFTL(((len)-1)/8, 19, 5) | \
       _SHIFTL((ofs)/8, 8, 8) | _SHIFTL((idx), 0, 8), \
       (u32)(uintptr_t)(adrs) }}

/* Viewport macro (F3DEX_GBI_2) */
#define gSPViewport(pkt, v) \
    gDma2p((pkt), G_MOVEMEM, (v), sizeof(Vp), G_MV_VIEWPORT, 0)

#define gsSPViewport(v) \
    gsDma2p(G_MOVEMEM, (v), sizeof(Vp), G_MV_VIEWPORT, 0)

/* LookAt macros */
#define gSPLookAtX(pkt, l) \
    gDma2p((pkt), G_MOVEMEM, (l), sizeof(Light), G_MV_LIGHT, G_MVO_LOOKATX)

#define gsSPLookAtX(l) \
    gsDma2p(G_MOVEMEM, (l), sizeof(Light), G_MV_LIGHT, G_MVO_LOOKATX)

#define gSPLookAtY(pkt, l) \
    gDma2p((pkt), G_MOVEMEM, (l), sizeof(Light), G_MV_LIGHT, G_MVO_LOOKATY)

#define gsSPLookAtY(l) \
    gsDma2p(G_MOVEMEM, (l), sizeof(Light), G_MV_LIGHT, G_MVO_LOOKATY)

#define gSPLookAt(pkt, la) \
{ \
    gSPLookAtX(pkt, la); \
    gSPLookAtY(pkt, (char*)(la) + 16); \
}

#define gsSPLookAt(la) \
    gsSPLookAtX(la), \
    gsSPLookAtY((char*)(la) + 16)

/* ============================================================================
 * Viewport and Scissor Macros
 * ============================================================================ */

#define gDPSetScissor(pkt, mode, ulx, uly, lrx, lry) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETSCISSOR, 24, 8) | _SHIFTL((ulx)*4, 12, 12) | _SHIFTL((uly)*4, 0, 12); \
    _g->words.w1 = _SHIFTL((mode), 24, 2) | _SHIFTL((lrx)*4, 12, 12) | _SHIFTL((lry)*4, 0, 12); \
}

#define G_SC_NON_INTERLACE  0
#define G_SC_ODD_INTERLACE  3
#define G_SC_EVEN_INTERLACE 2

/* ============================================================================
 * Clip Ratio Constants
 * ============================================================================ */

#define FRUSTRATIO_1    1
#define FRUSTRATIO_2    2
#define FRUSTRATIO_3    3
#define FRUSTRATIO_4    4
#define FRUSTRATIO_5    5
#define FRUSTRATIO_6    6

#define FR_NEG_FRUSTRATIO_1     0x00000001
#define FR_POS_FRUSTRATIO_1     0x0000ffff
#define FR_NEG_FRUSTRATIO_2     0x00000002
#define FR_POS_FRUSTRATIO_2     0x0000fffe
#define FR_NEG_FRUSTRATIO_3     0x00000003
#define FR_POS_FRUSTRATIO_3     0x0000fffd
#define FR_NEG_FRUSTRATIO_4     0x00000004
#define FR_POS_FRUSTRATIO_4     0x0000fffc
#define FR_NEG_FRUSTRATIO_5     0x00000005
#define FR_POS_FRUSTRATIO_5     0x0000fffb
#define FR_NEG_FRUSTRATIO_6     0x00000006
#define FR_POS_FRUSTRATIO_6     0x0000fffa

/* ============================================================================
 * Clip Ratio Macros
 * ============================================================================ */

#define gSPClipRatio(pkt, r) \
{ \
    gMoveWd(pkt, G_MW_CLIP, G_MWO_CLIP_RNX, FR_NEG_##r); \
    gMoveWd(pkt, G_MW_CLIP, G_MWO_CLIP_RNY, FR_NEG_##r); \
    gMoveWd(pkt, G_MW_CLIP, G_MWO_CLIP_RPX, FR_POS_##r); \
    gMoveWd(pkt, G_MW_CLIP, G_MWO_CLIP_RPY, FR_POS_##r); \
}

#define gsSPClipRatio(r) \
    gsMoveWd(G_MW_CLIP, G_MWO_CLIP_RNX, FR_NEG_##r), \
    gsMoveWd(G_MW_CLIP, G_MWO_CLIP_RNY, FR_NEG_##r), \
    gsMoveWd(G_MW_CLIP, G_MWO_CLIP_RPX, FR_POS_##r), \
    gsMoveWd(G_MW_CLIP, G_MWO_CLIP_RPY, FR_POS_##r)

/* ============================================================================
 * Fog Position Macro
 * ============================================================================ */

#define gSPFogPosition(pkt, min, max) \
    gMoveWd(pkt, G_MW_FOG, G_MWO_FOG, \
            (_SHIFTL((128000/((max)-(min))), 16, 16) | \
             _SHIFTL(((500-(min))*256/((max)-(min))), 0, 16)))

#define gsSPFogPosition(min, max) \
    gsMoveWd(G_MW_FOG, G_MWO_FOG, \
            (_SHIFTL((128000/((max)-(min))), 16, 16) | \
             _SHIFTL(((500-(min))*256/((max)-(min))), 0, 16)))

/* ============================================================================
 * OtherMode Shift/Mask Values
 * ============================================================================ */

#define G_MDSFT_CYCLETYPE       20
#define G_MDSFT_RGBDITHER       6
#define G_MDSFT_ALPHADITHER     4
#define G_MDSFT_COMBKEY         8
#define G_MDSFT_TEXTFILT        12
#define G_MDSFT_TEXTLUT         14
#define G_MDSFT_TEXTLOD         16
#define G_MDSFT_TEXTDETAIL      17
#define G_MDSFT_TEXTPERSP       19
#define G_MDSFT_PIPELINE        23
#define G_MDSFT_ALPHACOMPARE    0
#define G_MDSFT_ZSRCSEL         2
#define G_MDSFT_RENDERMODE      3

/* SetOtherMode macros */
#define gSPSetOtherMode(pkt, cmd, sft, len, data) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL((cmd), 24, 8) | _SHIFTL((32-(sft)-(len)), 8, 8) | _SHIFTL((len)-1, 0, 8); \
    _g->words.w1 = (u32)(data); \
}

#define gsSPSetOtherMode(cmd, sft, len, data) \
    {{ _SHIFTL((cmd), 24, 8) | _SHIFTL((32-(sft)-(len)), 8, 8) | _SHIFTL((len)-1, 0, 8), (u32)(data) }}

/* Cycle type */
#define gDPSetCycleType(pkt, type) \
    gSPSetOtherMode(pkt, G_SETOTHERMODE_H, G_MDSFT_CYCLETYPE, 2, type)

#define gsDPSetCycleType(type) \
    gsSPSetOtherMode(G_SETOTHERMODE_H, G_MDSFT_CYCLETYPE, 2, type)

/* Color dither */
#define gDPSetColorDither(pkt, mode) \
    gSPSetOtherMode(pkt, G_SETOTHERMODE_H, G_MDSFT_RGBDITHER, 2, mode)

#define gsDPSetColorDither(mode) \
    gsSPSetOtherMode(G_SETOTHERMODE_H, G_MDSFT_RGBDITHER, 2, mode)

/* ============================================================================
 * Color Setting Macros
 * ============================================================================ */

#define gDPSetColor(pkt, c, d) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL((c), 24, 8); \
    _g->words.w1 = (u32)(d); \
}

#define gsDPSetColor(c, d) \
    {{ _SHIFTL((c), 24, 8), (u32)(d) }}

#define gDPSetFogColor(pkt, r, g, b, a) \
    gDPSetColor(pkt, G_SETFOGCOLOR, \
        (_SHIFTL((r), 24, 8) | _SHIFTL((g), 16, 8) | _SHIFTL((b), 8, 8) | _SHIFTL((a), 0, 8)))

#define gsDPSetFogColor(r, g, b, a) \
    gsDPSetColor(G_SETFOGCOLOR, \
        (_SHIFTL((r), 24, 8) | _SHIFTL((g), 16, 8) | _SHIFTL((b), 8, 8) | _SHIFTL((a), 0, 8)))

#define gDPSetBlendColor(pkt, r, g, b, a) \
    gDPSetColor(pkt, G_SETBLENDCOLOR, \
        (_SHIFTL((r), 24, 8) | _SHIFTL((g), 16, 8) | _SHIFTL((b), 8, 8) | _SHIFTL((a), 0, 8)))

#define gsDPSetBlendColor(r, g, b, a) \
    gsDPSetColor(G_SETBLENDCOLOR, \
        (_SHIFTL((r), 24, 8) | _SHIFTL((g), 16, 8) | _SHIFTL((b), 8, 8) | _SHIFTL((a), 0, 8)))

/* ============================================================================
 * Sync Macros
 * ============================================================================ */

#define gDPNoParam(pkt, cmd) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL((cmd), 24, 8); \
    _g->words.w1 = 0; \
}

#define gsDPNoParam(cmd) \
    {{ _SHIFTL((cmd), 24, 8), 0 }}

#define gDPTileSync(pkt)    gDPNoParam(pkt, G_RDPTILESYNC)
#define gsDPTileSync()      gsDPNoParam(G_RDPTILESYNC)
#define gDPLoadSync(pkt)    gDPNoParam(pkt, G_RDPLOADSYNC)
#define gsDPLoadSync()      gsDPNoParam(G_RDPLOADSYNC)

/* ============================================================================
 * Scissor Macros (Static Version)
 * ============================================================================ */

#define gsDPSetScissor(mode, ulx, uly, lrx, lry) \
    {{ _SHIFTL(G_SETSCISSOR, 24, 8) | _SHIFTL((ulx)*4, 12, 12) | _SHIFTL((uly)*4, 0, 12), \
       _SHIFTL((mode), 24, 2) | _SHIFTL((lrx)*4, 12, 12) | _SHIFTL((lry)*4, 0, 12) }}

/* ============================================================================
 * Fill Rectangle Macros (Static Version)
 * ============================================================================ */

#define gsDPFillRectangle(xl, yl, xh, yh) \
    {{ _SHIFTL(G_FILLRECT, 24, 8) | _SHIFTL((xh), 12, 12) | _SHIFTL((yh), 0, 12), \
       _SHIFTL((xl), 12, 12) | _SHIFTL((yl), 0, 12) }}

/* ============================================================================
 * Scissor Texture Rectangle Macro
 * ============================================================================ */

/* Scissor-adjusted texture rectangle (same as regular for now) */
#define gSPScisTextureRectangle(pkt, xl, yl, xh, yh, tile, s, t, dsdx, dtdy) \
    gSPTextureRectangle(pkt, xl, yl, xh, yh, tile, s, t, dsdx, dtdy)

/* ============================================================================
 * RDP Half Macros (for multi-command sequences)
 * ============================================================================ */

#define gsImmp1(c, p0) \
    {{ _SHIFTL((c), 24, 8), (u32)(p0) }}

#define gImmp1(pkt, c, p0) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL((c), 24, 8); \
    _g->words.w1 = (u32)(p0); \
}

/* ============================================================================
 * Object/Sprite Macros (stubs for compatibility)
 * ============================================================================ */

#define gSPObjRectangle(pkt, sp) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_OBJ_RECTANGLE, 24, 8); \
    _g->words.w1 = (u32)(uintptr_t)(sp); \
}

#define G_OBJ_RECTANGLE     0x02
#define G_OBJ_SPRITE        0x04

/* ============================================================================
 * Render Mode Macros
 * ============================================================================ */

/* Alpha compare */
#define G_AC_NONE           0
#define G_AC_THRESHOLD      1
#define G_AC_DITHER         3

/* Z source select */
#define G_ZS_PIXEL          0
#define G_ZS_PRIM           1

/* Common render modes - placeholders for compatibility */
#define G_RM_OPA_SURF       0
#define G_RM_OPA_SURF2      0
#define G_RM_XLU_SURF       0
#define G_RM_XLU_SURF2      0
/* Render mode constants - stubs for PC port (actual blending handled by OpenGL) */
#define G_RM_ZB_OPA_SURF        0
#define G_RM_ZB_OPA_SURF2       0
#define G_RM_ZB_XLU_SURF        0
#define G_RM_ZB_XLU_SURF2       0
#define G_RM_FOG_SHADE_A        0
#define G_RM_AA_ZB_TEX_EDGE     0
#define G_RM_AA_ZB_TEX_EDGE2    0
#define G_RM_AA_ZB_OPA_SURF     0
#define G_RM_AA_ZB_OPA_SURF2    0
#define G_RM_AA_ZB_OPA_DECAL    0
#define G_RM_AA_ZB_OPA_DECAL2   0
#define G_RM_AA_ZB_XLU_SURF     0
#define G_RM_AA_ZB_XLU_SURF2    0
#define G_RM_OPA_SURF           0
#define G_RM_OPA_SURF2          0
#define G_RM_XLU_SURF           0
#define G_RM_XLU_SURF2          0

#define gDPSetRenderMode(pkt, c0, c1) \
{ \
    Gfx* _g = (Gfx*)(pkt); \
    _g->words.w0 = _SHIFTL(G_SETOTHERMODE_L, 24, 8) | _SHIFTL(3, 8, 8) | _SHIFTL(29, 0, 8); \
    _g->words.w1 = (u32)((c0) | (c1)); \
}

/* Static version for initializer lists */
#define gsDPSetRenderMode(c0, c1) \
    {{ _SHIFTL(G_SETOTHERMODE_L, 24, 8) | _SHIFTL(3, 8, 8) | _SHIFTL(29, 0, 8), \
       (u32)((c0) | (c1)) }}

/* Static version of SetPrimColor */
#define gsDPSetPrimColor(minlevel, lodfrac, r, g, b, a) \
    {{ _SHIFTL(G_SETPRIMCOLOR, 24, 8) | _SHIFTL((minlevel), 8, 8) | _SHIFTL((lodfrac), 0, 8), \
       _SHIFTL((r), 24, 8) | _SHIFTL((g), 16, 8) | _SHIFTL((b), 8, 8) | _SHIFTL((a), 0, 8) }}

/* ============================================================================
 * Lighting Constants and Macros
 * ============================================================================ */

#define NUMLIGHTS_0     0
#define NUMLIGHTS_1     1
#define NUMLIGHTS_2     2
#define NUMLIGHTS_3     3
#define NUMLIGHTS_4     4
#define NUMLIGHTS_5     5
#define NUMLIGHTS_6     6
#define NUMLIGHTS_7     7

/* Compute the number of lights value for G_MW_NUMLIGHT */
#define NUML(n) (((n)+1)*24)

/* Set number of lights */
#define gSPNumLights(pkt, n) \
    gMoveWd(pkt, G_MW_NUMLIGHT, G_MWO_NUMLIGHT, NUML(n))

#define gsSPNumLights(n) \
    gsMoveWd(G_MW_NUMLIGHT, G_MWO_NUMLIGHT, NUML(n))

/* Set light (F3DEX_GBI_2) */
#define gSPLight(pkt, l, n) \
    gDma2p((pkt), G_MOVEMEM, (l), sizeof(Light), G_MV_LIGHT, (n)*24+24)

#define gsSPLight(l, n) \
    gsDma2p(G_MOVEMEM, (l), sizeof(Light), G_MV_LIGHT, (n)*24+24)

/* Set all lights at once */
#define gSPSetLights1(pkt, name) \
{ \
    gSPNumLights(pkt, NUMLIGHTS_1); \
    gSPLight(pkt, &(name).l[0], 1); \
    gSPLight(pkt, &(name).a, 2); \
}

#define gsSPSetLights1(name) \
    gsSPNumLights(NUMLIGHTS_1), \
    gsSPLight(&(name).l[0], 1), \
    gsSPLight(&(name).a, 2)

/* Define lights structures */
#define gdSPDefLights0(ar, ag, ab) \
    { {{ {ar, ag, ab}, 0, {ar, ag, ab}, 0}}, \
      {{{ {0, 0, 0}, 0, {0, 0, 0}, 0, {0, 0, 0}, 0}}} }

#define gdSPDefLights1(ar, ag, ab, r1, g1, b1, x1, y1, z1) \
    { {{ {ar, ag, ab}, 0, {ar, ag, ab}, 0}}, \
      {{{ {r1, g1, b1}, 0, {r1, g1, b1}, 0, {x1, y1, z1}, 0}}} }

/* ============================================================================
 * GBI Interpreter Interface
 * ============================================================================ */

/* Initialize the GBI interpreter (OpenGL context must be ready) */
void gbi_init(void);

/* Shutdown the GBI interpreter */
void gbi_shutdown(void);

/* Execute a display list */
void gbi_execute(Gfx* dl);

/* Test function: Draw a triangle using the GBI vertex pipeline */
void gbi_draw_test_triangle(void);

/* Diagnostic: Draw identity triangle (confirms OpenGL is working) */
void gbi_test_identity_triangle(void);

/* Diagnostic: Log matrix state for debugging coordinate issues */
void gbi_log_matrix_state(const char* context);

/* Set framebuffer for rendering */
void gbi_set_framebuffer(void* fb, int width, int height);

/* Set a segment base address (N64 segmented memory support) */
void gbi_set_segment(int segment, void* addr);

/* Set translation offset for the next display list execution */
void gbi_set_translation(f32 x, f32 y, f32 z);

/* Apply the current translation to OpenGL modelview matrix */
void gbi_apply_translation(void);

/* Clear the translation offset */
void gbi_clear_translation(void);

#endif /* PC_GBI_H */
