/*
 * Proactive AC-Decomp Integration Updates
 * =======================================
 * Generated by proactive AC-decomp scanner
 * Contains placeholder types and functions found missing in AC-decomp source
 */

#ifndef AC_VITA_PROACTIVE_WRAPPER_UPDATES_H
#define AC_VITA_PROACTIVE_WRAPPER_UPDATES_H

// Only declare types that are NOT already defined in gx_to_vitagl_wrapper.h
// Removed: Gsetimg, Light_t, LookAt, Hilite, Ambient, Vp (already in main wrapper)
// Removed: OSThread, OSPriority (already in main wrapper)

// Matrix function that may be missing (only if not defined by sys_matrix.h)
#ifndef MATRIX_ROTATEVECTOR_DEFINED
extern void Matrix_RotateVector(void);
#endif

#endif // AC_VITA_PROACTIVE_WRAPPER_UPDATES_H
