#!/usr/bin/env python3
"""
Extract data symbol dependencies from actor files.

Scans actor source files for `extern` declarations that are DATA (not functions),
and reports which symbols need to be stubbed for linking.

Data symbols are detected by:
- extern declarations without () before ;
- Common patterns: *_tex, *_model, *_vtx, cKF_*, *_pal

Usage:
    python3 tools/extract_data_deps.py [--actor FILE] [--generate-stubs]
"""

import argparse
import re
from collections import defaultdict
from pathlib import Path
from typing import List, Dict, Set, Tuple

ACTOR_DIR = "src/actor"

# Pattern to match extern declarations
# extern TYPE name[]; or extern TYPE name;
EXTERN_PATTERN = re.compile(
    r'extern\s+(\w+(?:\s+\w+)*)\s+(\w+)\s*(\[[^\]]*\])?\s*;',
    re.MULTILINE
)

# Pattern to detect function prototypes (has parentheses)
FUNC_PROTO_PATTERN = re.compile(r'extern\s+\w+.*\([^)]*\)\s*;')

# Known data type prefixes/suffixes
DATA_PREFIXES = ['cKF_bs_', 'cKF_ba_', 'cKF_']
DATA_SUFFIXES = ['_tex', '_pal', '_model', '_vtx', '_tlut', '_dl', '_gfx']


def is_data_symbol(type_str: str, name: str) -> bool:
    """Determine if a symbol is likely data (not a function)."""
    # Check for known data patterns
    for prefix in DATA_PREFIXES:
        if name.startswith(prefix):
            return True
    for suffix in DATA_SUFFIXES:
        if name.endswith(suffix):
            return True

    # Array declarations are data
    # Pointer types that aren't function pointers
    if type_str in ['u8', 'u16', 'u32', 's8', 's16', 's32', 'f32', 'Gfx', 'Vtx',
                    'cKF_Skeleton_R_c', 'cKF_Animation_R_c', 'Mtx']:
        return True

    return False


def extract_data_deps(filepath: Path) -> List[Tuple[str, str, str]]:
    """Extract data dependencies from a C file.

    Returns list of (type, name, array_suffix) tuples.
    """
    deps = []

    try:
        content = filepath.read_text(errors='ignore')
    except Exception as e:
        print(f"Warning: Could not read {filepath}: {e}")
        return deps

    # Find all extern lines
    for line in content.split('\n'):
        line = line.strip()
        if not line.startswith('extern'):
            continue

        # Skip function prototypes
        if '(' in line and ')' in line:
            continue

        # Parse the declaration
        match = EXTERN_PATTERN.match(line)
        if match:
            type_str = match.group(1)
            name = match.group(2)
            array_suffix = match.group(3) or ''

            if is_data_symbol(type_str, name):
                deps.append((type_str, name, array_suffix))

    return deps


def categorize_symbol(name: str) -> str:
    """Categorize a symbol by its type."""
    if name.startswith('cKF_bs_'):
        return 'skeleton'
    elif name.startswith('cKF_ba_'):
        return 'animation'
    elif name.startswith('cKF_'):
        return 'keyframe_other'
    elif name.endswith('_tex'):
        return 'texture'
    elif name.endswith('_pal') or name.endswith('_tlut'):
        return 'palette'
    elif name.endswith('_model') or name.endswith('_dl') or name.endswith('_gfx'):
        return 'display_list'
    elif name.endswith('_vtx'):
        return 'vertex'
    else:
        return 'other'


def generate_stub_code(deps: Dict[str, List[Tuple[str, str, str]]]) -> str:
    """Generate C code to stub all the data symbols."""
    lines = []
    lines.append("/**")
    lines.append(" * @file asset_stubs.c")
    lines.append(" * @brief Auto-generated stubs for missing asset data symbols")
    lines.append(" *")
    lines.append(" * Generated by: python3 tools/extract_data_deps.py --generate-stubs")
    lines.append(" *")
    lines.append(" * These are zero-initialized stubs that satisfy the linker.")
    lines.append(" * Replace with real asset data as it becomes available.")
    lines.append(" */")
    lines.append("")
    lines.append('#include "types.h"')
    lines.append('#include "libforest/gbi_extensions.h"')
    lines.append('#include "PR/gbi.h"')
    lines.append("")
    lines.append("/* cKF types - minimal stubs */")
    lines.append("typedef struct { int dummy; } cKF_Skeleton_R_c;")
    lines.append("typedef struct { int dummy; } cKF_Animation_R_c;")
    lines.append("")

    # Group by category
    by_category = defaultdict(list)
    all_symbols = set()

    for actor, actor_deps in deps.items():
        for type_str, name, array_suffix in actor_deps:
            if name not in all_symbols:
                all_symbols.add(name)
                cat = categorize_symbol(name)
                by_category[cat].append((type_str, name, array_suffix))

    # Generate stubs by category
    category_order = ['skeleton', 'animation', 'keyframe_other', 'texture',
                      'palette', 'display_list', 'vertex', 'other']

    for cat in category_order:
        if cat not in by_category:
            continue

        lines.append(f"/* === {cat.upper()} === */")

        for type_str, name, array_suffix in sorted(by_category[cat], key=lambda x: x[1]):
            if cat == 'skeleton':
                lines.append(f"cKF_Skeleton_R_c {name} = {{0}};")
            elif cat == 'animation':
                lines.append(f"cKF_Animation_R_c {name} = {{0}};")
            elif cat in ['texture', 'palette']:
                # Default to 64 bytes for textures
                lines.append(f"u8 {name}[64] = {{0}};")
            elif cat == 'display_list':
                lines.append(f"Gfx {name}[] = {{ gsSPEndDisplayList() }};")
            elif cat == 'vertex':
                lines.append(f"Vtx {name}[1] = {{{{{{0}}}}}};")
            else:
                # Generic stub
                if array_suffix:
                    lines.append(f"{type_str} {name}{array_suffix} = {{0}};")
                else:
                    lines.append(f"{type_str} {name} = {{0}};")

        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Extract data dependencies from actors")
    parser.add_argument("--actor", "-a", help="Analyze specific actor file")
    parser.add_argument("--generate-stubs", "-g", action="store_true",
                        help="Generate asset_stubs.c file")
    parser.add_argument("--output", "-o", default="src/pc/asset_stubs.c",
                        help="Output file for stubs")
    parser.add_argument("--title-demo", "-t", action="store_true",
                        help="Only analyze TITLE_DEMO actors")

    args = parser.parse_args()

    # Find project root
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    actor_path = project_root / ACTOR_DIR

    # TITLE_DEMO actor files
    title_demo_files = {
        'ac_animal_logo.c', 'ac_birth_control.c', 'ac_dummy.c',
        'ac_effectbg.c', 'ac_field_draw.c', 'ac_fieldm_draw.c',
        'ac_quest_manager.c', 'ac_structure.c', 'ac_tools.c',
        'ac_weather.c', 'ac_uki.c', 'ac_handOverItem.c'
    }

    # Collect dependencies
    all_deps: Dict[str, List[Tuple[str, str, str]]] = {}

    if args.actor:
        # Single actor
        filepath = project_root / args.actor
        deps = extract_data_deps(filepath)
        all_deps[filepath.name] = deps
    else:
        # All actors (or TITLE_DEMO subset)
        actor_files = list(actor_path.glob("*.c"))

        for actor_file in sorted(actor_files):
            if args.title_demo and actor_file.name not in title_demo_files:
                continue

            deps = extract_data_deps(actor_file)
            if deps:
                all_deps[actor_file.name] = deps

    # Print report
    print("=" * 70)
    print("DATA DEPENDENCY REPORT")
    print("=" * 70)
    print()

    # Count symbols by category
    all_symbols = set()
    by_category = defaultdict(set)

    for actor, deps in all_deps.items():
        for type_str, name, _ in deps:
            all_symbols.add(name)
            by_category[categorize_symbol(name)].add(name)

    print(f"Actors analyzed: {len(all_deps)}")
    print(f"Unique data symbols needed: {len(all_symbols)}")
    print()

    print("By category:")
    for cat in ['skeleton', 'animation', 'texture', 'palette', 'display_list', 'vertex', 'other']:
        if cat in by_category:
            print(f"  {cat:<15} {len(by_category[cat]):>4} symbols")
    print()

    # Per-actor breakdown
    print("-" * 70)
    print("PER-ACTOR BREAKDOWN")
    print("-" * 70)

    for actor in sorted(all_deps.keys()):
        deps = all_deps[actor]
        print(f"\n{actor} ({len(deps)} data deps):")
        for type_str, name, array_suffix in deps[:10]:
            cat = categorize_symbol(name)
            print(f"  [{cat:<12}] {name}")
        if len(deps) > 10:
            print(f"  ... and {len(deps) - 10} more")

    # Generate stubs if requested
    if args.generate_stubs:
        print()
        print("-" * 70)
        print("GENERATING STUBS")
        print("-" * 70)

        stub_code = generate_stub_code(all_deps)
        output_path = project_root / args.output

        print(f"Writing to: {output_path}")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(stub_code)

        print(f"Generated stubs for {len(all_symbols)} symbols")
        print()
        print("Add to CMakeLists.txt:")
        print(f"    {args.output}")

    print()
    print("Done!")
    return 0


if __name__ == "__main__":
    exit(main())
