/**
 * @file m_actor_dlftbls_pc.c
 * @brief PC-specific actor profile table
 *
 * AUTO-GENERATED by tools/generate_actor_table.py
 * Do not edit manually - edit tools/approved_actors.json instead.
 *
 * Approved actors: 11/246
 */

#include "m_actor_dlftbls.h"
#include "m_actor.h"

/* Headers for approved actors */
#include "ac_animal_logo.h"
#include "ac_birth_control.h"
#include "ac_dummy.h"
#include "ac_dump.h"
#include "ac_effectbg.h"
#include "ac_field_draw.h"
#include "ac_fieldm_draw.h"
#include "ac_my_house.h"
#include "ac_structure.h"
#include "ac_weather.h"
#include "m_player_call.h"

/* Number of actor profiles */
int actor_dlftbls_num = mAc_PROFILE_NUM;

/* Stub entry (NULL profile) */
#define S {0, 0, NULL, NULL, NULL, NULL, 0, 0, 0, 0}

/* Profile entry macro */
#define P(actor) {0, 0, NULL, NULL, NULL, &actor##_Profile, 0, 0, 0, 0}

/*
 * The actor profile table
 *
 * Approved actors:
 *   [0] = mAc_PROFILE_PLAYER -> Player_Profile
 *   [3] = mAc_PROFILE_FIELDM_DRAW -> Fieldm_Draw_Profile
 *   [4] = mAc_PROFILE_FIELD_DRAW -> Field_Draw_Profile
 *   [119] = mAc_PROFILE_EFFECTBG -> Effectbg_Profile
 *   [171] = mAc_PROFILE_ANIMAL_LOGO -> Animal_Logo_Profile
 *   [49] = mAc_PROFILE_BIRTH_CONTROL -> Birth_Control_Profile
 *   [55] = mAc_PROFILE_WEATHER -> Weather_Profile
 *   [69] = mAc_PROFILE_STRUCTURE -> Structure_Profile
 *   [43] = mAc_PROFILE_MYHOUSE -> MyHouse_Profile
 *   [166] = mAc_PROFILE_DUMP -> Dump_Profile
 *   [180] = mAc_PROFILE_DUMMY -> Dummy_Profile
 */
ACTOR_DLFTBL actor_dlftbls[mAc_PROFILE_NUM] = {
    /*   0-  9 */ P(Player), S, S, P(Fieldm_Draw), P(Field_Draw), S, S, S, S, S, /* 0=PLAYER, 3=FIELDM_DRAW, 4=FIELD_DRAW */
    /*  10- 19 */ S, S, S, S, S, S, S, S, S, S,
    /*  20- 29 */ S, S, S, S, S, S, S, S, S, S,
    /*  30- 39 */ S, S, S, S, S, S, S, S, S, S,
    /*  40- 49 */ S, S, S, P(MyHouse), S, S, S, S, S, P(Birth_Control), /* 43=MYHOUSE, 49=BIRTH_CONTROL */
    /*  50- 59 */ S, S, S, S, S, P(Weather), S, S, S, S, /* 55=WEATHER */
    /*  60- 69 */ S, S, S, S, S, S, S, S, S, P(Structure), /* 69=STRUCTURE */
    /*  70- 79 */ S, S, S, S, S, S, S, S, S, S,
    /*  80- 89 */ S, S, S, S, S, S, S, S, S, S,
    /*  90- 99 */ S, S, S, S, S, S, S, S, S, S,
    /* 100-109 */ S, S, S, S, S, S, S, S, S, S,
    /* 110-119 */ S, S, S, S, S, S, S, S, S, P(Effectbg), /* 119=EFFECTBG */
    /* 120-129 */ S, S, S, S, S, S, S, S, S, S,
    /* 130-139 */ S, S, S, S, S, S, S, S, S, S,
    /* 140-149 */ S, S, S, S, S, S, S, S, S, S,
    /* 150-159 */ S, S, S, S, S, S, S, S, S, S,
    /* 160-169 */ S, S, S, S, S, S, P(Dump), S, S, S, /* 166=DUMP */
    /* 170-179 */ S, P(Animal_Logo), S, S, S, S, S, S, S, S, /* 171=ANIMAL_LOGO */
    /* 180-189 */ P(Dummy), S, S, S, S, S, S, S, S, S, /* 180=DUMMY */
    /* 190-199 */ S, S, S, S, S, S, S, S, S, S,
    /* 200-209 */ S, S, S, S, S, S, S, S, S, S,
    /* 210-219 */ S, S, S, S, S, S, S, S, S, S,
    /* 220-229 */ S, S, S, S, S, S, S, S, S, S,
    /* 230-239 */ S, S, S, S, S, S, S, S, S, S,
    /* 240-245 */ S, S, S, S, S, S,
};

/* Verify array size at compile time */
_Static_assert(sizeof(actor_dlftbls) / sizeof(actor_dlftbls[0]) == mAc_PROFILE_NUM,
               "actor_dlftbls must have exactly mAc_PROFILE_NUM entries");

#undef S
#undef P

/*
 * Initialize the actor dlftbls.
 */
void actor_dlftbls_init(void) {
    /* Table is initialized statically */
}

/*
 * Cleanup actor dlftbls.
 */
void actor_dlftbls_cleanup(void) {
    /* Nothing to clean up */
}
