/**
 * @file terrain_loader.c
 * @brief Load terrain binary blobs and set up segment registers
 *
 * This loader reads binary files generated by terrain_to_bin.py and:
 * 1. Allocates a buffer for the terrain data
 * 2. Sets up segment 8 for vertices, segment 9 for textures
 * 3. Returns pointers to vertex data and display lists
 *
 * Version 2 format includes:
 * - Complete GBI display lists (texture setup, render mode, triangles)
 * - Texture reference table for runtime binding
 * - Dolphin-specific GBI commands
 */

#include "pc/gbi.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Binary format constants */
#define ACRE_MAGIC "ACRE"
#define ACRE_VERSION_1 1
#define ACRE_VERSION_2 2
#define HEADER_SIZE_V2 64

/* Fixed segment assignments (same as terrain_to_bin.py) */
#define SEG_VERTICES 8
#define SEG_TEXTURES 9

/* Version 1 header (32 bytes) - legacy format */
typedef struct {
    char magic[4];
    u32 version;
    u32 segment_id;
    u32 vtx_offset;
    u32 vtx_count;
    u32 dl_offset;
    u32 dl_size;
    u32 reserved;
} AcreHeaderV1;

/* Version 2 header (64 bytes) - full format with textures */
typedef struct {
    char magic[4];      /* "ACRE" */
    u32 version;        /* 2 */
    u32 flags;          /* Reserved flags */
    u32 vtx_offset;     /* Offset to vertex data */
    u32 vtx_count;      /* Number of vertices */
    u32 dl_offset;      /* Offset to display list */
    u32 dl_cmd_count;   /* Number of Gfx commands (not bytes) */
    u32 tex_count;      /* Number of texture references */
    u32 tex_table_offset; /* Offset to texture reference table */
    u8 reserved[28];    /* Padding to 64 bytes */
} AcreHeaderV2;

/* Texture reference entry (8 bytes) */
typedef struct {
    u32 name_hash;      /* Hash of texture name */
    u32 seg_offset;     /* Offset within segment 9 */
} TextureRefEntry;

typedef struct {
    void* buffer;           /* Allocated buffer for terrain data */
    u32 buffer_size;        /* Size of allocated buffer */
    u32 version;            /* Binary format version */
    Vtx* vertices;          /* Pointer to vertex data */
    u32 vtx_count;          /* Number of vertices */
    Gfx* display_list;      /* Pointer to display list */
    u32 dl_cmd_count;       /* Number of Gfx commands */
    TextureRefEntry* textures; /* Texture reference table */
    u32 tex_count;          /* Number of texture references */
} LoadedTerrain;

/* External: GBI segment setter */
extern void gbi_set_segment(int segment, void* addr);

/* Currently loaded terrain */
static LoadedTerrain g_loaded_terrain = {0};

/* External: texture buffer from texture_registry.c */
extern void* texture_get_buffer(void);

/**
 * Load a terrain binary file (supports v1 and v2 formats).
 * @param path Path to .bin file
 * @return 0 on success, -1 on failure
 */
int terrain_load_bin(const char* path) {
    FILE* f = fopen(path, "rb");
    if (!f) {
        printf("[TERRAIN_LOADER] Failed to open: %s\n", path);
        return -1;
    }

    /* Get file size */
    fseek(f, 0, SEEK_END);
    long file_size = ftell(f);
    fseek(f, 0, SEEK_SET);

    /* Read magic and version first */
    char magic[4];
    u32 version;
    if (fread(magic, 1, 4, f) != 4 || fread(&version, 4, 1, f) != 1) {
        printf("[TERRAIN_LOADER] Failed to read header: %s\n", path);
        fclose(f);
        return -1;
    }
    fseek(f, 0, SEEK_SET);

    /* Validate magic */
    if (memcmp(magic, ACRE_MAGIC, 4) != 0) {
        printf("[TERRAIN_LOADER] Invalid magic: %s\n", path);
        fclose(f);
        return -1;
    }

    /* Free previous terrain if any */
    if (g_loaded_terrain.buffer) {
        free(g_loaded_terrain.buffer);
        memset(&g_loaded_terrain, 0, sizeof(g_loaded_terrain));
    }

    /* Allocate buffer for entire file */
    void* buffer = malloc(file_size);
    if (!buffer) {
        printf("[TERRAIN_LOADER] Failed to allocate %ld bytes\n", file_size);
        fclose(f);
        return -1;
    }

    /* Read entire file */
    if (fread(buffer, 1, file_size, f) != (size_t)file_size) {
        printf("[TERRAIN_LOADER] Failed to read file data\n");
        free(buffer);
        fclose(f);
        return -1;
    }
    fclose(f);

    g_loaded_terrain.buffer = buffer;
    g_loaded_terrain.buffer_size = file_size;
    g_loaded_terrain.version = version;

    printf("[TERRAIN_LOADER] Loading: %s (v%u)\n", path, version);

    if (version == ACRE_VERSION_1) {
        /* Version 1: Legacy format */
        AcreHeaderV1* hdr = (AcreHeaderV1*)buffer;

        g_loaded_terrain.vertices = (Vtx*)((u8*)buffer + hdr->vtx_offset);
        g_loaded_terrain.vtx_count = hdr->vtx_count;
        g_loaded_terrain.display_list = (Gfx*)((u8*)buffer + hdr->dl_offset);
        g_loaded_terrain.dl_cmd_count = hdr->dl_size / 8;  /* Convert bytes to commands */
        g_loaded_terrain.textures = NULL;
        g_loaded_terrain.tex_count = 0;

        /* Set segment register */
        gbi_set_segment(hdr->segment_id, g_loaded_terrain.vertices);

        printf("[TERRAIN_LOADER]   Segment: %u\n", hdr->segment_id);
        printf("[TERRAIN_LOADER]   Vertices: %u at offset %u\n",
               hdr->vtx_count, hdr->vtx_offset);
        printf("[TERRAIN_LOADER]   DL: %u bytes at offset %u\n",
               hdr->dl_size, hdr->dl_offset);

    } else if (version == ACRE_VERSION_2) {
        /* Version 2: Full format with textures */
        AcreHeaderV2* hdr = (AcreHeaderV2*)buffer;

        g_loaded_terrain.vertices = (Vtx*)((u8*)buffer + hdr->vtx_offset);
        g_loaded_terrain.vtx_count = hdr->vtx_count;
        g_loaded_terrain.display_list = (Gfx*)((u8*)buffer + hdr->dl_offset);
        g_loaded_terrain.dl_cmd_count = hdr->dl_cmd_count;

        if (hdr->tex_count > 0 && hdr->tex_table_offset > 0) {
            g_loaded_terrain.textures = (TextureRefEntry*)((u8*)buffer + hdr->tex_table_offset);
            g_loaded_terrain.tex_count = hdr->tex_count;
        } else {
            g_loaded_terrain.textures = NULL;
            g_loaded_terrain.tex_count = 0;
        }

        /* Set segment 8 for vertices */
        gbi_set_segment(SEG_VERTICES, g_loaded_terrain.vertices);

        /* Set segment 9 for textures (use texture registry buffer) */
        void* tex_buf = texture_get_buffer();
        if (tex_buf) {
            gbi_set_segment(SEG_TEXTURES, tex_buf);
            printf("[TERRAIN_LOADER]   Texture segment 9: %p\n", tex_buf);
        }

        printf("[TERRAIN_LOADER]   Vertices: %u at offset %u\n",
               hdr->vtx_count, hdr->vtx_offset);
        printf("[TERRAIN_LOADER]   DL: %u commands at offset %u\n",
               hdr->dl_cmd_count, hdr->dl_offset);
        printf("[TERRAIN_LOADER]   Textures: %u refs at offset %u\n",
               hdr->tex_count, hdr->tex_table_offset);

    } else {
        printf("[TERRAIN_LOADER] Unsupported version %u: %s\n", version, path);
        free(buffer);
        return -1;
    }

    printf("[TERRAIN_LOADER]   Buffer: %p\n", buffer);
    printf("[TERRAIN_LOADER]   Vertices ptr: %p\n", (void*)g_loaded_terrain.vertices);
    printf("[TERRAIN_LOADER]   DL ptr: %p\n", (void*)g_loaded_terrain.display_list);
    printf("[TERRAIN_LOADER] Loaded successfully!\n");

    return 0;
}

/**
 * Get the display list for the loaded terrain.
 * Returns the direct pointer to the display list.
 */
Gfx* terrain_get_loaded_dl(void) {
    if (!g_loaded_terrain.buffer) {
        return NULL;
    }

    printf("[TERRAIN_LOADER] Returning DL ptr: %p (%u commands)\n",
           (void*)g_loaded_terrain.display_list, g_loaded_terrain.dl_cmd_count);

    return g_loaded_terrain.display_list;
}

/**
 * Get number of commands in loaded display list.
 */
int terrain_get_cmd_count(void) {
    return g_loaded_terrain.dl_cmd_count;
}

/**
 * Get info about loaded terrain.
 */
int terrain_get_vertex_count(void) {
    return g_loaded_terrain.vtx_count;
}

/**
 * Unload terrain and free resources.
 */
void terrain_unload(void) {
    if (g_loaded_terrain.buffer) {
        /* Clear segment registers */
        gbi_set_segment(SEG_VERTICES, NULL);
        if (g_loaded_terrain.version == ACRE_VERSION_2) {
            gbi_set_segment(SEG_TEXTURES, NULL);
        }

        free(g_loaded_terrain.buffer);
        memset(&g_loaded_terrain, 0, sizeof(g_loaded_terrain));
        printf("[TERRAIN_LOADER] Terrain unloaded\n");
    }
}

/**
 * Look up full 64-bit pointer for binary terrain addresses.
 * Used by seg2ptr to recover truncated heap pointers.
 */
void* terrain_bin_get_fullptr(u32 truncated_addr) {
    if (!g_loaded_terrain.buffer) return NULL;

    /* Check if this is the display list */
    u32 dl_trunc = (u32)(uintptr_t)g_loaded_terrain.display_list;
    if (truncated_addr == dl_trunc) {
        static int dl_debug = 0;
        if (dl_debug < 3) {
            printf("[TERRAIN_BIN_FULLPTR] DL match: 0x%08X -> %p\n",
                   truncated_addr, (void*)g_loaded_terrain.display_list);
            dl_debug++;
        }
        return g_loaded_terrain.display_list;
    }

    /* Check if this is within the buffer (vertices, DL data, etc.) */
    u32 buf_base = (u32)(uintptr_t)g_loaded_terrain.buffer;
    u32 buf_end = buf_base + g_loaded_terrain.buffer_size;
    if (truncated_addr >= buf_base && truncated_addr < buf_end) {
        u32 offset = truncated_addr - buf_base;
        void* result = (u8*)g_loaded_terrain.buffer + offset;
        static int buf_debug = 0;
        if (buf_debug < 5) {
            printf("[TERRAIN_BIN_FULLPTR] Buffer match: 0x%08X (offset 0x%X) -> %p\n",
                   truncated_addr, offset, result);
            buf_debug++;
        }
        return result;
    }

    return NULL;
}
